### ISSUE TITLE
[PE-D][Tester E] Join feature: Students from other tutorial group can join groups for other tutorial group

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F12-2/tp#159]
Groups are created based on the tutorial number. However, student with no tutorial group or in other tutorial group can join any groups in any given tutorial.

![image.png](https://raw.githubusercontent.com/yanghengtang/ped/main/files/796e29c0-a4ac-40a0-8b79-b29628f3282e.png)

Just to show the added students are with no tutorial from other tutorial:
![image.png](https://raw.githubusercontent.com/yanghengtang/ped/main/files/db8f1308-dbfb-4c93-a2de-2899093fcc9a.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: yanghengtang/ped#4

**Comment by PearlynnT** [comment]
Add a tip box in the UG to explain this
