### ISSUE TITLE
[PE-D][Tester E] Check Group feature: Confusion between "requirement" and "encouraged" 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F12-2/tp#167]
For a group with all same gender it returns:

![image.png](https://raw.githubusercontent.com/yanghengtang/ped/main/files/89e65a64-5984-459f-b114-a41b986ad25e.png)

But in your help window it states it is not a requirement, just an encouragement, so the Check Group should return a more appropriate message.
![image.png](https://raw.githubusercontent.com/yanghengtang/ped/main/files/b5b18351-5759-46fe-bedd-5bf54918e35f.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yanghengtang/ped#5

**Comment by PearlynnT** [comment]
Change warning message
